name: Build Multi-Platform

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Use stable version, not 3.14
      
      - name: Install ffmpeg
        run: brew install ffmpeg
      
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      
      - name: Build macOS App
        run: |
          source venv/bin/activate
          chmod +x build.sh
          ./build.sh
      
      - name: Upload macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: macOS-DMG
          path: PixelTraivo-YT-Downloader-macOS.dmg
          retention-days: 90

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install ffmpeg
        run: |
          choco install ffmpeg -y
      
      - name: Install dependencies
        run: |
          python -m venv venv
          venv\Scripts\activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      
      - name: Build Windows EXE
        run: |
          venv\Scripts\activate
          pyinstaller --name="PixelTraivo-YT-Downloader" --windowed --onefile --noconfirm --clean --icon=assets\icon.ico --add-binary="C:\ProgramData\chocolatey\bin\ffmpeg.exe;." --add-binary="C:\ProgramData\chocolatey\bin\ffprobe.exe;." --add-data="assets;assets" --hidden-import=yt_dlp --hidden-import=tkinter main.py
      
      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: Windows-EXE
          path: dist/PixelTraivo-YT-Downloader.exe
          retention-days: 90

  create-release:
    needs: [build-macos, build-windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: macOS-DMG
          path: ./artifacts
      
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: Windows-EXE
          path: ./artifacts
      
      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/PixelTraivo-YT-Downloader-macOS.dmg
            ./artifacts/PixelTraivo-YT-Downloader.exe
          body: |
            # 🎉 PixelTraivo YouTube Downloader ${{ steps.version.outputs.VERSION }}
            
            ## 📥 Download & Install
            
            ### 🍎 macOS
            1. Download `PixelTraivo-YT-Downloader-macOS.dmg`
            2. Open DMG file
            3. Drag app to Applications folder
            4. Right-click app → Open (first time only)
            
            ### 🪟 Windows
            1. Download `PixelTraivo-YT-Downloader.exe`
            2. Double-click to run
            3. If SmartScreen warning: Click "More info" → "Run anyway"
            
            ## ✨ Features
            - 🎬 High-quality video downloads (up to 1080p)
            - 🎵 MP3 audio extraction (320kbps)
            - 📊 Real-time progress tracking
            - 🎨 Beautiful modern dark UI
            - ⚡ Fast downloads with resume support
            - 📁 Custom download location
            - 🔄 Built-in ffmpeg (no extra installation needed)
            
            ## 🆕 What's New
            - ✅ Standalone builds with bundled ffmpeg
            - ✅ No external dependencies required
            - ✅ Improved error handling
            - ✅ Better progress tracking
            
            ## 🐛 Bug Reports
            Found an issue? [Report it here](https://github.com/${{ github.repository }}/issues)
            
            ---
            
            **Made with ❤️ by Pixel Traivo**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}